Add overview doc
gro-intelligence/api-client pull request #100
Opened 2019-08-16 19:56 UTC by JGrinst

Text summary for Prevent Plant, in support of the notebook. Supporting overviews like this are desired for every model.

2019-08-27 14:17 UTC, itsjohnward requested changes

2019-08-27 14:17 UTC, itsjohnward commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +[SMOS Soil Moisture](https://app.gro-intelligence.com/dictionary/sources/43)
SMOS is appearing on the same line as "Corn Prevent Plant Model Inputs" in the rendered page. Looks like a bug. Supposed to be bulleted?

2019-08-27 14:17 UTC, itsjohnward commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +*Note, in addition to inputs used for the corn model, the soybean model includes the following:*
Similar to SMOS above, this note is not bulleted and so shows up on the same line as "Soybean Prevent Plant Model Inputs"

2019-08-27 14:17 UTC, itsjohnward commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +*Note, in addition to the corn model methodology, the soybean model includes the following:*
Add bullet to this note too

2019-08-27 14:17 UTC, itsjohnward commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +** Weeks are defined by the planting progress date.
Should this be a single bullet instead of double? Showing up right on the same line as XGBoost. The double-star looks like XGBoost has a footnote

2019-08-27 14:17 UTC, itsjohnward commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +*Note, in addition to inputs used for the corn model, the soybean model includes the following:*
Perhaps you meant to surround this line with blank lines to get it to show up, unbulleted, between the title and the list

2019-08-27 14:17 UTC, itsjohnward commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +*Note, in addition to the corn model methodology, the soybean model includes the following:*
Or surround with blank lines

2019-08-27 17:57 UTC, JGrinst commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +[SMOS Soil Moisture](https://app.gro-intelligence.com/dictionary/sources/43)
I think all these formatting issues are resolved now.

2019-08-27 18:58 UTC, itsjohnward approved these changes

2019-08-27 23:06 UTC, tolothy requested changes

2019-08-27 23:06 UTC, tolothy commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +* __Model Specific Data:__ “Area prevented, non-irrigated” data to determine acres that have not been planted in the current crop year due to an inability to plant the crop. The final prevent plant n
"released by the FSA in January" is not accurate. It is partially released in August, and FSA will keep updating it until next year.

2019-08-27 23:06 UTC, tolothy commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +* Test cumulative soil moisture and weekly precipitation signals from week 14 (beginning of April) to the current week along with planting progress using XGBoost. Weeks are defined by the planting pr
XGBoost or Grandient Boosting regressor

2019-08-27 23:06 UTC, tolothy commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +* Test weekly soil moisture (average) and precipitation (cumulative) from week 16 (second half of April) to the current week along with planting progress and soil characteristics using XGBoost.
same as above about XGBoost

2019-08-27 23:06 UTC, tolothy commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +* National report on planting progress tends to end by week 23 (early June), but state level data will be reported for another week or two if planting is delayed. Incorporating state level data for 2
that's already done (included in the current version of notebook)

2019-08-28 07:17 UTC, nemozen approved these changes
lgtm.

2019-08-28 07:17 UTC, nemozen commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +* __Model Specific Data:__ “Area prevented, non-irrigated” data to determine acres that have not been planted in the current crop year due to an inability to plant the crop. The final prevent plant n
yes but what we are trying to predict is the final number that is released in january, not the interim estimates, right?

2019-08-28 13:43 UTC, tolothy commented on api/client/samples/prevented_plant/prevent-plant-model-overview.md
> +* __Model Specific Data:__ “Area prevented, non-irrigated” data to determine acres that have not been planted in the current crop year due to an inability to plant the crop. The final prevent plant n
correct.

2019-08-28 14:51 UTC, tolothy approved these changes

2019-08-28 14:51 UTC, tolothy approved these changes

2019-08-28 14:54 UTC, merged