Don't retry 401/404/500
gro-intelligence/api-client pull request #101
Opened 2019-08-23 13:21 UTC by alexsherman

Small change in the get_data retry loop to break if the error code indicates not found, unauthorized, or server error. This prevents retrying in obvious cases where the token is invalid or the URL is wrong but also should prevent retrying in the case reported in the issue where rank_series_by_source was returning a 404.

```
lib.get_data('http://api.gro-intelligence.com/v2/available/sources', '')
->
{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "api/client/lib.py", line 170, in get_data
    url, retry_count, data.text))
Exception: Giving up on http://api.gro-intelligence.com/v2/available/sources after 1 tries. Error is: {"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}.
```

```
lib.get_data('http://api.gro-intelligence.com/asdfjhlkj', '')
->
{"statusCode":404,"error":"Not Found"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "api/client/lib.py", line 170, in get_data
    url, retry_count, data.text))
Exception: Giving up on http://api.gro-intelligence.com/asdfjhlkj after 1 tries. Error is: {"statusCode":404,"error":"Not Found"}.
```

2019-08-23 21:32 UTC, itsjohnward requested changes
Tested:

```py
import os
from api.client.gro_client import GroClient

API_HOST = 'api.gro-intelligence.com'
ACCESS_TOKEN = os.environ['GROAPI_TOKEN']

def main():
    client = GroClient(API_HOST, ACCESS_TOKEN)
    client.lookup('regions', 2)

if __name__ == "__main__":
    main()
```

```py
$ python 404.py

{"statusCode":404,"error":"Not Found"}
Traceback (most recent call last):
  File "404.py", line 12, in <module>
    main()
  File "404.py", line 9, in main
    client.lookup('regions', 2)
  File "/Users/john/.local/share/virtualenvs/api-work-2lr6jHLN/lib/python2.7/site-packages/api/client/__init__.py", line 20, in lookup
    return lib.lookup(self.access_token, self.api_host, entity_type, entity_id)
  File "/Users/john/.local/share/virtualenvs/api-work-2lr6jHLN/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 113, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/john/.local/share/virtualenvs/api-work-2lr6jHLN/lib/python2.7/site-packages/api/client/lib.py", line 266, in lookup
    resp = get_data(url, headers)
  File "/Users/john/.local/share/virtualenvs/api-work-2lr6jHLN/lib/python2.7/site-packages/api/client/lib.py", line 170, in get_data
    url, retry_count, data.text))
Exception: Giving up on https://apistage11201.gro-intelligence.com/v2/regions/2 after 1 tries. Error is: {"statusCode":404,"error":"Not Found"}.
```

Works as expected.

Only comment is remove the semicolon https://lintlyci.github.io/Flake8Rules/rules/E703.html

2019-08-26 13:31 UTC, alexsherman commented
Done

2019-08-26 13:43 UTC, itsjohnward approved these changes

2019-08-26 21:44 UTC, muzigao approved these changes

2019-08-26 21:44 UTC, merged