Update custom-theme.css
gro-intelligence/api-client pull request #110
Opened 2019-09-20 14:13 UTC by musenlin-gro

addressed the issues on this jira ticket: https://grointelligence.atlassian.net/browse/CLEWS-20910
1. Adjust width of page, so that it's more centered like most documentation sites
2. Re-instate "view source" button to return to the github page with the source info.

2019-11-14 22:25 UTC, itsjohnward requested changes

2019-11-14 22:25 UTC, itsjohnward commented on docs/_static/css/custom-theme.css
> +    height: 100vh;
This added height property is causing the grey background to cut off below the fold. See https://developers.gro-intelligence.com/musenlin-gro-patch-1/api.html and try scrolling

2019-12-06 16:25 UTC, itsjohnward approved these changes

2019-12-06 16:48 UTC, JGrinst commented
Page looks great!

2019-12-06 16:48 UTC, JGrinst approved these changes

2019-12-06 17:09 UTC, merged