Direct git to ignore commonly untracked Python and Jetbrains files.
gro-intelligence/api-client pull request #171
Opened 2020-02-25 13:27 UTC by MichaelWakahe

This is a .gitignore file with files that should not be tracked by git.

2020-02-25 15:03 UTC, itsjohnward requested changes
Looks all right, but I think it's somewhat overkill - left some comments on irrelevant lines so we can slim it down a bit to what's really necessary.

Also, let's consolidate `api/.gitignore`, `docs/.gitignore`, and `r-client/.gitignore` up into this one

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +docs/_build/
We have this in `docs/.gitignore` currently. Can remove one or the other

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +*.py[cod]
Ignoring `.pyc` in api/.gitignore currently. Should be able to remove that file

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +.idea/
Might as well add these for VSCode as well:

```py
.vscode/*
*.code-workspace
```

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +/site
We are using sphinx, rather than mkdocs, so this one can be excluded

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +.pytype/
I would like to add mypy at some point, but currently we're not using any of these type checkers (mypy, pyre, pytype). So I think we can exclude them until it's relevant

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +.ropeproject
Not using rope currently

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +celerybeat.pid
Nothing celery-related in this repo. Can use the API client in a celery task, but scheduling and all that would not go in this package. Can exclude

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +#Pipfile.lock
We can uncomment to ignore Pipfile.lock.
You want it committed in an *application*, like what we deploy to our servers, but not in an installable package. Here, we want requirements to be as permissive as possible so it doesn't cause unnecessary conflicts in installers' environments.

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +# .python-version
Can uncomment to ignore. We support many different python versions - shouldn't need to specify a specific one with pyenv

2020-02-25 15:03 UTC, itsjohnward commented on .gitignore
> +target/
Not using PyBuilder - can remove

2020-10-23 15:08 UTC, jli commented
the major parts of this were added in #264, thanks @MichaelWakahe !

2020-10-23 15:08 UTC, closed without merging