DELI-276 include historical refactor for get_descendant()
gro-intelligence/api-client pull request #341
Opened 2022-02-15 16:10 UTC by yohn-dezmon

Previously get_descendant() made a call to `v2/regions/contains` to get the descendant ids for a given region, then if include_historical was set to false, it would do batch lookups of the descendant ids against the `v2/regions` endpoint. After getting a response, it would filter the data for the regions that had include_historical set to false.

This PR is directly related to the DELI-276 PR on the `gro/api` code base, where the includeHistorical parameter was added to the `/v2/reginos/contains` endpoint as an optional parameter. Thus, now the filtering for the historical regions is done at the DB level, and unnecessary processing at the python API client is no longer necessary.

2022-02-16 12:22 UTC, cn1036 commented on groclient/lib.py
> +    if not include_historical:
minor: can simply use `params['includeHistorical'] = include_historical`

2022-02-16 12:28 UTC, cn1036 requested changes
one minor comment, otherwise lgtm

2022-02-16 14:21 UTC, yohn-dezmon commented on groclient/lib.py
> +    if not include_historical:
good call, updating now.

2022-02-16 15:39 UTC, cn1036 approved these changes

2022-02-16 15:40 UTC, cn1036 commented
waiting for the prod release

2022-03-03 21:48 UTC, muzigao-gro approved these changes

2022-03-03 21:48 UTC, merged