CLEWS-18068 Allow insert_null as a get_data_points input
gro-intelligence/api-client pull request #69
Opened 2019-05-31 19:21 UTC by itsjohnward

Allow using `insert_null` with `get_data_series()`.

Test script:

```python
import os
from api.client.gro_client import GroClient

API_HOST = 'api.gro-intelligence.com'
ACCESS_TOKEN = os.environ['GROAPI_TOKEN']

def main():
    client = GroClient(API_HOST, ACCESS_TOKEN)
    
    for point in client.get_data_points(
        metric_id=2100031,
        item_id=2165,
        region_id=1000003252,
        source_id=22,
        insert_null=True
    ):
        print(point['start_date'], point['value'])

if __name__ == "__main__":
    main()
```

Returns `None` values where normally they'd be excluded:

```
2018-11-15T00:00:00.000Z 88.2
2018-11-16T00:00:00.000Z 2.8000000000000003
2018-11-17T00:00:00.000Z None
2018-11-18T00:00:00.000Z None
2018-11-19T00:00:00.000Z None
2018-11-20T00:00:00.000Z 0
2018-11-21T00:00:00.000Z 0
2018-11-22T00:00:00.000Z 0
2018-11-23T00:00:00.000Z 3.2
```

2019-06-05 16:28 UTC, nemozen approved these changes

2019-06-05 16:30 UTC, nemozen requested changes
also update the doc string

2019-06-05 17:07 UTC, itsjohnward commented
@nemozen done!

2019-06-06 17:38 UTC, nemozen approved these changes

2019-06-06 17:39 UTC, merged