J grinst patch 3
gro-intelligence/api-client pull request #93
Opened 2019-08-08 22:31 UTC by JGrinst

I'm proposing here to create a new folder - within the crop models folder - for collecting all of the needed information for the Brazil Soybeans model.

There should be:
README
brazil_soybeans.ipynb
requirements.txt
__init__

2019-08-09 13:42 UTC, itsjohnward requested changes
Tested and working on Mac Python 2.7.16 and Windows Anaconda Python 2.7.16 with the addition of the `descartes` package mentioned below

2019-08-09 13:42 UTC, itsjohnward commented on api/client/samples/crop_models/brazil_soybeans/README.md
> +### Run prevented plant
Brazil soybeans*

2019-08-09 13:42 UTC, itsjohnward commented on api/client/samples/crop_models/brazil_soybeans/requirements.txt
> +jupyter
Need to add `descartes`

2019-08-12 19:47 UTC, JGrinst commented on api/client/samples/crop_models/brazil_soybeans/requirements.txt
> +jupyter
Done

2019-08-12 19:47 UTC, JGrinst commented on api/client/samples/crop_models/brazil_soybeans/README.md
> +### Run prevented plant
Done

2019-08-22 17:22 UTC, itsjohnward approved these changes

2019-09-20 15:24 UTC, merged